# Generated by Django 4.2.7 on 2023-11-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('message', models.TextField(blank=True, max_length=200)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
